# Exception Handling Error Type ( Built in Error )

# Built in error you can handle but syntax error you can't handle

# try and except block
# try -> try the code
# except - execute except code (if problem try)
# We can use two or more except in one program when using finally

# try :
#     # Try this code , if error
# except:
#     # Excute me if try has some error

'''
Syntax :-  try:
               [ Program Statement where exception might occur ]
           except[exception_name]:
               [ Code for exception handling if the exception_name error is encountered ]
'''

# This is normal program

# num1=int(input("Enter the first number :"))
# num2=int(input("Enter the second number :"))
# divide=num1/num2
# print("Division :",divide)
# print("Program end")
# here if I enter any number divide by zero so got ZeroDivisionError that's why we use exception handling




# num1=int(input("Enter the first number :"))
# num2=int(input("Enter the second number :"))
# try:
#     divide=num1/num2
#     print("Division :",divide)
# except:
#     print("oop error find")
#     print("Program end")







